//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://localhost:49408/signalrdemo.html");
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://localhost:49408/favicon.ico");
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://localhost:49408/signalr/negotiate");
            request3.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=UTF-8"));
            request3.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request3.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://localhost:49408/signalrdemo.html"));
            request3.QueryStringParameters.Add("clientProtocol", "1.4", false, false);
            request3.QueryStringParameters.Add("connectionData", "%5B%7B%22name%22%3A%22simohub%22%7D%5D", false, false);
            request3.QueryStringParameters.Add("_", "1526571692835", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://localhost:49408/signalr/start");
            request4.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=UTF-8"));
            request4.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request4.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://localhost:49408/signalrdemo.html"));
            request4.QueryStringParameters.Add("transport", "webSockets", false, false);
            request4.QueryStringParameters.Add("clientProtocol", "1.4", false, false);
            request4.QueryStringParameters.Add("connectionToken", "%2FCyQwIpB2HxWY1B5Jg9LIULUUsb7Fkd1ehguvV23dy9BAQbFpEGnFVD0q3MSVwru%2BrIY0FbGhm4md" +
                    "ovUKVvhVLJXXsBeiV98Z%2FFaRap3KRRcTGHOhpCAV6Spp06KQQjk", false, false);
            request4.QueryStringParameters.Add("connectionData", "%5B%7B%22name%22%3A%22simohub%22%7D%5D", false, false);
            request4.QueryStringParameters.Add("_", "1526571692836", false, false);
            yield return request4;
            request4 = null;
        }
    }
}
